title: Taylor Sheridan # your name (or website title) here
logo: "/images/T-2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  <a href="https://www.linkedin.com/in/tsheridan7251/">LinkedIn</a> 
  <br>
  <a href="/pdf/TaylorSheridan_Resume_03.09.23.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/TSheridan25">GitHub</a> 
  <br>
  
theme: jekyll-theme-minimal
